/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope;
// eslint-disable-next-line @typescript-eslint/naming-convention
declare const __WB_MANIFEST: unknown;

import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, NetworkOnly } from "workbox-strategies";

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
clientsClaim();

cleanupOutdatedCaches();

// Precache all assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://vite-pwa-org.netlify.app/guide/inject-manifest.html
precacheAndRoute(self.__WB_MANIFEST);

// IMPORTANT: Bypass caching for all API requests
// This includes REST API calls, SSE streams, and WebSocket fallbacks
// The /api/ path should never be cached as it contains dynamic data
registerRoute(({ url }) => url.pathname.startsWith("/api/"), new NetworkOnly());

// Also bypass any localhost API server (for development)
registerRoute(
  ({ url }) => url.hostname === "localhost" && url.pathname.includes("/api/"),
  new NetworkOnly()
);

// Cache Google Fonts Stylesheet
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: "google-fonts-cache",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Cache Google Fonts Webfonts
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: "gstatic-fonts-cache",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
    ],
  })
);

// Handle Push Notifications
self.addEventListener("push", (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const title = data.title || "New Notification";
    const options: NotificationOptions = {
      body: data.message || "You have a new message",
      icon: "/pwa-192x192.png",
      badge: "/pwa-192x192.png",
      data: data.url || "/", // Store URL to open on click
      tag: data.tag || "default",
    };

    // Broadcast the push data to all active clients (React app)
    event.waitUntil(
      self.clients
        .matchAll({ type: "window", includeUncontrolled: true })
        .then((clients) => {
          clients.forEach((client) => {
            client.postMessage({
              type: "PUSH_RECEIVED",
              payload: {
                ...data,
                id: data.id || Date.now().toString(),
                timestamp: data.timestamp || new Date().toISOString(),
              },
            });
          });
        })
    );

    event.waitUntil(self.registration.showNotification(title, options));
  } catch (err) {
    console.error("Error parsing push data:", err);
  }
});

// Handle Notification Click
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data;

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients) => {
        // Check if there is already a window open with this URL
        for (const client of windowClients) {
          if (client.url === urlToOpen && "focus" in client) {
            return client.focus();
          }
        }
        // If not, open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
  );
});
